generation_task:
  description: >
    Provide a concise response to the user's query - {query}, 
    using only the provided knowledge - {context}.
    If the provided knowledge is not sufficient to answer the user's query,
    acknowledge that you do not have sufficient information to answer the user's query,
    and ask the user to either rephrase their question or to contact customer support.
  expected_output: >
    A brief and concise response that directly answers the user's query in a customer-friendly manner.
  agent: generator
