generation_task:
  description: >
    Respond to the customer's query: {query}
    Utilize the following context to inform your response:\n\n{context}
    If the context is insufficient, politely ask the customer for clarification
    or suggest alternative support channels.
  expected_output: >
    A short, direct and professional response, no more than 5 sentences, that either answers the customer's query or informs them that sufficient information
    is unavailable. If it is the latter, the response should include alternative ways for the customer to seek
    assistance.
  agent: generator

formatting_task:
  description: >
    Format the customer support representative's response to ensure it is clear, concise, and well-structured
    for easy readability. Use bullet points, line breaks, and appropriate punctuation to improve readability.
    Ensure the response remains professional and is easy for the customer to understand.
    Remove information that does not directly answer the customer's query: {query}
  expected_output: >
    A well-structured, clear, and concise response that is easy for the customer to understand.
    Uses formatting elements like bullet points, or spacing where necessary.
    Retains the original meaning without adding information.
  agent: formatter
