generation_task:
  description: >
    Respond to the customer's query: {query}
    Utilize the following context to inform your response:\n\n{context}
    If the context is insufficient, politely ask the customer for clarification
    or suggest alternative support channels.
  expected_output: >
    A short, direct and professional response, no more than 5 sentences, that either answers the customer's query or informs them that sufficient information
    is unavailable. If it is the latter, the response should include alternative ways for the customer to seek
    assistance.
  agent: generator
